name: CI|CD learning
on: workflow_dispatch
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Project build is getting ready
        run: echo "Build successfully"
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Test the build
        run: echo "Tests passes sucessfully"
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Pushing the code to vm
        run: echo "Code Pushed successfully"
