name: Learning CI|CD
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build the project
        run: echo "Build Completed"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing the project
        run: echo "Test cases passed"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the code
        run: echo "Deployed Successfully"
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the admin
        run: echo "Sent notification successfully"
